version: "3.9"
services:
  tg-proxy:
    build: .
    image: kpihx/tg-proxy:latest
    container_name: tg-proxy
    volumes:
      - ~/.config/tg-proxy:/root/.config/tg-proxy
      - ~/.config/tg:/root/.config/tg
    network_mode: host
    environment:
      - TG_API_ID=${TG_API_ID}
      - TG_API_HASH=${TG_API_HASH}
